use_frameworks!

platform :ios, '8.0'

target 'RFTangram_Example' do
  pod 'RFTangram', :path => '../'

  target 'RFTangram_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
